### ISSUE TITLE
Creature Skills

### ISSUE THREAD

**Issue by jaqual** [Heliomance/HeroForge-Anew#111]
I know this is a simple fix, just figured you maybe would not like to have to trace it down..

The skills list after "Iaijutsu Focus" are one column number off for the Index function.  Intimidate's column value('Familiar', DA16) is 8, while in 'TblFamiliarSkills' on 'Creature Info' it is the ninth column, as eighth column is "Iaijutsu Focus."  Before and after. just changing the numbers by one:

![image](https://cloud.githubusercontent.com/assets/28215696/25562452/068eff04-2d4c-11e7-8e11-bda14a731127.png)

![image](https://cloud.githubusercontent.com/assets/28215696/25562433/c0a76fe4-2d4b-11e7-8dd5-3b0aeecece5b.png)

**Comment by Heliomance** [comment]
Looks like this issue is no longer relevant due to the sheet restructure in 8.0. Closing ticket.
