### ISSUE TITLE
Items in Name Manager pointing to a file in your Documents folder

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#12]
Not a real issue but just thought I'd let you know that there are some items in the Name Manager that are pointing to a Heroforge in your Document folder.
The items are MsESeer1, MsESeer1, MsEShp1, MSEShp2, MsETele1, MsETele2, and TblTemplateClassSk. I'm pretty sure that those wont work properly if they point to someplace that doesn't exist for other users.

**Comment by torrasque666** [comment]
The MsE stuff are relics from my codes for the Psion ACFs. Dunno about TblTemplateClassSk though.

**Comment by TwistedFaith84** [comment]
ok the TblTemplateClassSk can be removed unless you want to add a skills section to Template Info. The MsE stuff if they are relics they can be removed? or are those needed still for something?

**Comment by torrasque666** [comment]
The MsE stuff can be removed. Heliomance must have missed them when she did clean up. She replaced them with much more appropriate names.

**Comment by Heliomance** [comment]
Got them.
