### ISSUE TITLE
7.4.0.1 xlsm bug?

### ISSUE THREAD

**Issue by Captain-Emo** [Heliomance/HeroForge-Anew#128]
Hello,

I've been using the old 7.4.0.0.xls for about a year and a half. I recently came to see this new 7.4.0.1.xlsm file and tried to use it. I selected a source from the Options tab, and the races from that book didn't populate. I tried selecting "Ignore sourcebooks selection" in the Race & Templates tab, but there are still no races beyond the PHB. I might have messed something up though, since it errored upon opening and I tried to fix the links.

Also, I've tried reaching out through Google Sites before. I really would like to help with this project in any way I can. I have 2 and soon 3 different groups only running 3.5 with no interest in moving to 5e. This sheet is used by everyone in my groups. I've made a few customizations to add in items from missing sources and some other odd things. 

Thanks!

**Comment by TwistedFaith84** [comment]
I would say to try redownload v7.4.0.1 again maybe something went wrong durning the download. As for Helping out yeah if you want to check out the issues tab and get all caught up with the majority of the conversations there that would help you get to know and understand where the project is currently.
