### ISSUE TITLE
No Place to ask for requests

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#14]
Not a prob but it would be nice if there was a place for requests. I know you have a list of stuff you wanna do I just figured that if enough people requested something that it would allow you to move that item up on your list. Also on that note just curious if you ever used the YAPCG? I only ask cause the way they have their Weapons And Magic Items would be a great way to do it for HeroForge if it wasn't to complicated.

**Comment by Heliomance** [comment]
I've not used YAPCG, but I'll have to take a look at that. Acomplete overhaul of the magic items stuff has been on my to-do list for a long time, stymied by the fact that |I don't know what I want to do with it. Thanks for the pointer!

As for requests, I have threads on minmaxboards, ENworld, and RPGnet, and there's also the HeroForge Yahoo group.

**Comment by TwistedFaith84** [comment]
Your welcome for the pointer about YAPCG. I think the way that they have their Weapons and Magic Items would be pretty good. It not only has spots for weapons, armor, specific weapons, and specific armor but it actually allows you to add (and auto calculate) magic properties. The only slight difference I would make with it if I was really any good at VBA would be instead of selecting from a drop down box what magical prop your weapon or armor has is leave a space where you can type in what props it has (separated by a comma) and heroforge will search fro those properties and calc. That way we aren't limited to only 3 especially when we are in epic level.

You'll see that it also has places for scrolls, potions, rods, and the like but also magical tattoos.
Granted it's nice you dont have to have the spells in heroforge for the scroll, potions, and wands. You just need to know whats on/in that item, how many charges, cost, and weight.
