### ISSUE TITLE
Monk Bonus Feats Drop-downs

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#17]
I noticed that some of the Monks Bonus Feats in the drop-down list are showing #Name? error. I know that there was some feats listed b4 Anew. I haven't played a monk in a while so I don't know when the error actually occurred.

**Comment by torrasque666** [comment]
It's from when she screwed up the Eberron campaign stuff.

Side note: Tashalatora isn't calculated for a lot of things.

**Comment by Heliomance** [comment]
_headdesk_
MORE Eberron stuff I broke? Dammit, I thought I fixed all that already.

What's Tashalatora missing? I implemented that ages ago, and I can't remember what I did and didn't do.

**Comment by torrasque666** [comment]
Mostly Flurry of blows so far. Dunno about much more

Sent from my Virgin Mobile Android-Powered Device

----- Reply message -----

**Comment by Heliomance** [comment]
I've got the Flurry of Blows fix done already, it'll be done in 7.4.

**Comment by TwistedFaith84** [comment]
out of curiosity about how much longer for 7.4
I don't want to hurry you or anything like that. I know each update takes time.

**Comment by Heliomance** [comment]
Not sure. 7.4 is adding Oriental Adventures, which is quite a lot of content - it may be a while.
