### ISSUE TITLE
Point Blank Shot not working properly

### ISSUE THREAD

**Issue by Gamingdevil** [Heliomance/HeroForge-Anew#18]
I noticed that Point Blank shot doesn't appear to be counting the damage bonus when "Within 30'" is chosen, although the attack bonus appears to be working fine.

I did some digging and I think it's because, on the Attacks tab, cell X20 only counts the bonuses between cells X11:X18, whereas it should also include X19.

Now, I must admit I didn't try to understand every piece of every formula, so I might be completely wrong, but X19 does at least seem to go to 1 when I chose either "Within 30'", or "Rapid Shot, Within 30'" and 0 for all other options.

This is for Weapon/Attack 2, for Attack 1, it's cell I20 and there are others for each attack.

Thanks for checking

**Comment by Heliomance** [comment]
Fixed in 7.4
