### ISSUE TITLE
Weapon "Inappropriately sized"

### ISSUE THREAD

**Issue by Zukibird** [Heliomance/HeroForge-Anew#20]
HeroForge Anew 3.5 v7.3.2.4

Firstly, Great job!

Secondly, when posting a new sheet please make sure all character data has already been cleared out.

Finally, I am trying to build a Nixie Bard. Whenever I pick any weapon, any size, I get a pop-up saying "Inappropriately Sized" and no weapon info shows up.

Thanks!

**Comment by Heliomance** [comment]
All character data has been cleared out of the latest stable release. If you look at the front page, you'll note it's very clearly marked "unstable development version". Download an older version. I put it up nice an conveniently on the Releases page.

**Comment by Heliomance** [comment]
Can't reproduce weapon size error
