### ISSUE TITLE
Familar And Animal Companion Skills.

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#22]
Hey Just wanted to let you know that I figured out what the Skills coding syntax  is on the Creatures Info Sheet. The 0;0, 2;4, 0;2 ect..
The first number is how many ranks in the skill the creature has the second number any and all modifiers such as Racial, Feat, Other, Speed, Size, Synergy. I figured this out by looking at the Skill Blocks for a variety of different monsters @ http://imarvintpa.com/dndlive/ If you wanna look for yourself. I dont know where they got the Skill Blocks for the monsters but they have them for some. (btw if you do go look at that website everything highlighted in blue is where the full info is and everything in orange only has miniscule amounts of data)

**Comment by Heliomance** [comment]
Will be changing skill syntax as part of version 8.0
