### ISSUE TITLE
Attacks showing #Value#

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#23]
hey I dont know if this is for all classes but for a Druid when you have your attacks listed for your weapons on the Attacks sheet and then you Wildshape to have the Attacks be added for the form you Wildshape into (ie Wildshape into a Black Bear go back to the Attacks sheet and add the 2 claws and bite to 2 slots of the attacks), when you revert back to normal form and you try to add new attacks everything comes ups as #VALUE# errors unless you reset the Attacks sheet.

**Comment by Heliomance** [comment]
...Wildshape's turned out to be a massive headache. I'll look into a solution, though I suspect the only thing I'll be able to do will mean you'll have to re-select the natural weapons every time you Wildshape.

**Comment by Heliomance** [comment]
Fixed in 7.4
