### ISSUE TITLE
Adding Heedless Charge to Power Attack Buff

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#25]
This isn't an issue but its something that would be nice if you could add. I can give you the steps if you want them. These steps are gonna act like you don't know what your doing in case some1 that doesn't know can do it for themselves.

1) Create a checkbox next to Power Attack. Leave enough space  between The power attack input cell and the checkbox so you can "name" the check box Headless Charge.

2) Open up Name Manager from FORMULAS tab with the checkbox selected (hold Ctrl+Click). Create a new Name and call it "HeedlessCharge". It should point to the checkbox.

3) Right click on checkbox and go to Format Control. Go to the Control Tab and in the Cell Link Type in Heedless Charge.

4) Go to the Attacks sheet and select rows 4-14 and unhide them also unhide all Columns. Go to cells F13, U13, AJ13, AY13, BN13, and CC13. your formula should look like this in F13
=IF(AND(PowerAttackAmount>0,OR(NOT(L14),AND(FtPowerThrow,L14)),NOT(HeedlessCharge)),PowerAttackAmount,0)+IF(AND(CombatExpertiseAmount>0,NOT(L14)),CombatExpertiseAmount,0)

5) The L14 in the formula should go with its respected counterparts so for U13 the formula would be
=IF(AND(PowerAttackAmount>0,OR(NOT(AA14),AND(FtPowerThrow,AA14))),PowerAttackAmount,0)+IF(AND(CombatExpertiseAmount>0,NOT(AA14)),CombatExpertiseAmount,0)

6) Continue till the 4 remaining are done.

7) Go to CS Calc sheet and in cell G50 your formula should be
=IF(HeedlessCharge,-PowerAttackAmount,0)

**Comment by Heliomance** [comment]
Ah, you forgot a bit. That won't be saved as part of the character file - to do that, the cell labelled HeedlessCharge that the checkbox links to needs to be on the ExportSheet tab. It also won't reset when you clear the sheet - doing that requires modifying the VBScript code.

**Comment by TwistedFaith84** [comment]
Yea that wasn't the only thing I forgot (which I didn't know that info). I also forgot that with Heedless Charge allows you to take a portion or all of the neg to Attack and transfer it to AC. So at +6 BAB you could go full power attack and use Heedless Charge to transfer atleast neg 1 off your To Hit and move it to your AC, or you can take all the neg 6 to your To Hit and transfer it to AC, or somewhere in between your min BAB to you max BAB and transfer that neg To Hit to AC. So it probably wouldn't be a checkbox thing.
