### ISSUE TITLE
Size U and M in Class Weapons And Armor?

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#26]
I was scrolling through and noticed 2 size types that I have no clue what they are, Curious if you know?
U: I'm guessing that this is for Unarmed as the only things listed with it is Gauntlet, Grapple, Touch, & Unarmed Strike.
M: I have no Idea. Has Listed Cat-O-Nine-Tails, Musket, Poker, & Rapier, Parthian.

**Comment by Heliomance** [comment]
U is indeed unarmed. I... have no idea what M is supposed to be, it doesn't seem to do anything. Looks like a bug to me, good catch. That said, I don't know where to find the stats for any of those weapons to fix them.

**Comment by nolan1989** [comment]
M probably stands for Medium, I guess

**Comment by TwistedFaith84** [comment]
I think the Parthian Rapier is from Ravenloft (according to Google search) as for the others IDK either except I thing Cat-O-Nine-Tails is actually refereed to Nine Tails and dndwiki (again google search) the others maybe Ravenloft or Dragonlance or Living Greyhawk.
