### ISSUE TITLE
Psion Discipline

### ISSUE THREAD

**Issue by AncestralD** [Heliomance/HeroForge-Anew#27]
There is a small bug under the psion class. The discipline Telepath and psychopotation is offset by two lines. but only the name. the stats and calculations are placet as if the discoplines were two lines above
![psion discipline](https://cloud.githubusercontent.com/assets/10347610/8159340/fd8d69a6-1365-11e5-9142-4f5e3bddea82.PNG)

**Comment by Heliomance** [comment]
Fixed in 8.0.
