### ISSUE TITLE
Request: Could you please add a 7th attack area.

### ISSUE THREAD

**Issue by Silinde** [Heliomance/HeroForge-Anew#28]
Hi,  I love that someone has taken up the continuation of this project.  I am just requesting that you add a 7th attack area.  I always add it myself but it is a bit time consuming to add it to every revision, besides it make the character sheet look more balanced when printed.

**Comment by Heliomance** [comment]
What on earth are you doing that needs more than 6 attacks?
I'm loath to, mostly because that would mean the Attacks page no longer fits nicely on one screen width. On the other hand, once I finally get around to doing the next version, if all goes to plan, hopefully you shouldn't need to add it to every revision. I plan on making it all more modular, as much as possible, so depending on how successful I am, you might not need to update the whole thing and lose your changes whenever a new version comes out.

**Comment by torrasque666** [comment]
So like, instead of having one spreadsheet, we'd have something more akin to a folder and a sheet for races, raceinfo, stats, magic items, and what not?

**Comment by Heliomance** [comment]
What I'm planning, if possible, is to move all of the hidden data tables out of the main sheet and into separate files, which the main sheet then references. Functionality should hopefully not be affected at all, but it would mean that, say, new creatures could be added and only the CreatureInfo file has to be updated. I haven't even started looking yet at how possible this will actually be (I'm quite busy at work at the moment) but that's the plan. I also hope to move all the VBScript code out into external files, and just have the in-sheet code call the relevant routines when necessary. It will make version control an awful lot more transparent - only the bits that actually change will ever need to be updated.

**Comment by Heliomance** [comment]
At the same time or subsequently, I'm also hoping to reintegrate MonsterForge and SpellForge, leaving them as their own files, but having them reading the same data tables. In the case of SpellForge, I'd also like to make it able to import HeroForge character files, to simplify the process of building a spellcaster. That's probably a fair way down the line though.

**Comment by Heliomance** [comment]
Long-term, I'd actually like to move away from Excel entirely, and rebuild the whole shebang as a standalone database app. That's a long way off though, and will require me to learn an awful lot more about databases and coding applications.

**Comment by nolan1989** [comment]
When you get to that, If you need help with databases and SQL, let me know.
I'm pretty decent with them.

**Comment by TwistedFaith84** [comment]
You know if thats the way you want to go with if then may I suggest PCGen. There all you would have to do is create custom files for 3.5 to add everything in. or you could go way old school and do ETools seeing that nobody really uses that anymore. The only problem I see with you going with a standalone app tho is if/when WOTC sees/hears about it your get alot of legal paperwork that will want you to stop.

**Comment by Heliomance** [comment]
The legal issues are going to be no different with a standalone app than with the Excel sheet - I'm violating copyright just as much either way. I do emphasise though, that that's a long way down the line. I'm not going to be doing that any time soon.

**Comment by TwistedFaith84** [comment]
Yea that's very true. Just trying to look out for you and everyone else. Also I figured that you wouldn't be doing that until a much later time. That is going to take alot of time to even just get going not to mention figuring out how it will all work together properly.

**Comment by Silinde** [comment]
Sorry I have been back in a while. but to anser your question Heliomance

For a seventh attack area:
You must be using a small monitor if 7 wont fit on one monitor expanse.
A seventh attack area makes the character sheet look better, (no white space at the bottom)
and I do things like this:

Attack 1
Long Sword 2weapon Primary
Attack 2
Short Sword 2weapon Secondary
Attack 3
Long Sword 1weapon
Attack 4
Short Sword 2weapon Primary
Attack 5
Dagger 2weapon secondary
Attack 6
Long Bow
Attack 7
Fist/Gauntlet/unarmed

Or:
Attack 1
LongBow [within 30']
Attack 2
Long Bow
Attack 3
LongBow [Rapid Shot]
Attack 4
LongBow [Rapid shot, within 30']
Attack 5
LongBow [Manyshot]
Attack 6
Long Sword
Attack 7
Dagger
