### ISSUE TITLE
Feature Request: Green Ronin APG Racial Customization Support

### ISSUE THREAD

**Issue by GamerGoddessDin** [Heliomance/HeroForge-Anew#32]
Title.  
.  
Preferably with an optional slot to load a base race to modify. For example one could select Human is said slot to load in the default Human properties before adding or modifying them.

**Comment by torrasque666** [comment]
All WotC content isn't even in yet, and if 3rd party support is to be added then it becomes a "where's the line drawn?" Type situation. Honestly, the Players Companion stuff should probably get gutted sometime soon too.

**Comment by GamerGoddessDin** [comment]
Good thing I was already planning on switching to BahamutDragon's PCGen data sets then. He's already got most of the commonly used official stuff and a fair amount of third party stuff too. The Green Ronin APG race stuff isn't in yet but at least he's mentioned it shouldn't be too hard for him to add it in fairly soon.
