### ISSUE TITLE
More Flaws

### ISSUE THREAD

**Issue by zerkeros** [Heliomance/HeroForge-Anew#33]
Hello, is it possible to add more flaws in the worksheet? And if yes, how can we do that?

**Comment by torrasque666** [comment]
what flaws did you want to add? Its not difficult if you just unhide a few columns on the flaws page.

**Comment by Heliomance** [comment]
I\t's possible to change literally anything about HeroForge. It's the great strength of having it be a spreadsheet app - everything is modifiable. That said, I've not looked into the format of the Flaws sheet, so I can't tell you how to do it offhand. As torrasque666 said, unhide the columns on the sheet and copy the format of the existing ones.

**Comment by TwistedFaith84** [comment]
I know this is closed but what Flaws are there that aren't in heroforge already?

**Comment by zerkeros** [comment]
all the flaws from dragon magazines  :P
