### ISSUE TITLE
Question / Pull Request

### ISSUE THREAD

**Issue by Chris-ScoutCorps** [Heliomance/HeroForge-Anew#34]
Before I just surprise you with a pull request, I figured I'd ask - I usually do my battle maps using Excel and a projector. One thing I've found very useful is just a sheet off to the side that's got pre-drawn shapes for each spell effect (radius, cone, line), so I can copy/paste one in real quick to figure out who got hit by a Fireball.

I was about to post it to my own GitHib, but then figured I wasn't the first one with that idea, did a few searches, and yours looks the most similar.

Is that something that you think would be worth including? Or are you trying to keep this concise and single-purpose?

**Comment by Heliomance** [comment]
That's not really something that belongs in HeroForge, I don't think. Useful idea, but no, I'd rather keep this project to do with character generation and suchlike.
