### ISSUE TITLE
Spellsheets

### ISSUE THREAD

**Issue by chaoscommencer** [Heliomance/HeroForge-Anew#35]
Hello, I've cloned the latest version of HeroForge and can't seem to get it to generate spell sheets.  In older versions spell sheets would be generated with the availability of spell selection appropriate to your character class(es) and level.  I've played around with it a bit and created a 20th level sorcerer as an example, including the Complete Arcane and Spell Compendium.  The familiar character sheet gets generated but not the spell sheets.  Is this a bug; am I missing step(s); or has this feature since been removed?

**Comment by torrasque666** [comment]
Dayum boy, how out of the loop are you? That was splintered off a long time ago into <a href="https://github.com/torrasque666/Spellforge-Anew">Spellforge</a>, which I took over but the updates are ridiculously tedious and slow.

**Comment by chaoscommencer** [comment]
Ah, cool, thanks for the update.  I'll check that out then.  Looks like the option to Load Character exists there.  I assume that's compatible with HeroForge character files?

**Comment by TwistedFaith84** [comment]
@chaoscommencer What version of HeroForge are have you been using? and also what other old version do you still have (if any)? Can you upload them? I'm a little bit of a collector.

**Comment by Heliomance** [comment]
No, it's not currently compatible with HeroForge character files. I plan to make it so at some point, but development on HeroForge is currently paused due to real life and other projects.

**Comment by chaoscommencer** [comment]
@TwistedFaith84 Sorry I didn't notice your request earlier. I think at least one version I have is like 3.x. I can upload a couple versions tomorrow if you'd like. Need a place to upload them to, though. Dropbox?

**Comment by chaoscommencer** [comment]
@torrasque666 do you know if Spellforge was splintered off due to size constraints/performance issues, or if it was due to some other reason?

**Comment by torrasque666** [comment]
Likely due to size. One time I tried to reintegrate it (adding in the spell sheets and the spell info pages) and it nearly doubled in size.

**Comment by chaoscommencer** [comment]
Ya, I kind of figured.  If size doesn't noticeably impact performance though, I think it would be cool if you could reintegrate it. It would make for a better user experience (having everything pertinent to your character in the same document).

**Comment by Heliomance** [comment]
I'm planning on semi-integrating it - having it as a separate document, but using the same save format as HF so you can import a character directly from one to the other.

**Comment by TwistedFaith84** [comment]
If you can 1 request I'd like to make is to also integrate Spell Points.
@chaoscommencer yea dropbox would be good but if any/all of your versions are on the site below I dont need them anymore. Just check the site and see first
http://nzcomputers.net/heroforge/downloads/

**Comment by chaoscommencer** [comment]
@TwistedFaith84
I have 3.5.50 (which I couldn't find at your link) and I have 6.0.1.10, which you appear to have already.

**Comment by TwistedFaith84** [comment]
ok cool I'll take 3.5.50 if you could send me a link.

**Comment by Heliomance** [comment]
If you could take this discussion to #53 I'd appreciate it. I'll close this issue down now as the original question has been answered.

**Comment by lagame** [comment]
Hello dear, I made a version for myself of Spellforge, and I am posting here if you are interested. I included the spells from the Complete Scoundrel book.
Example of grimoire with new wizard spells:
https://imgur.com/a/0gV7RJv

Spellforge 4.5.2:
https://drive.google.com/file/d/1WFdQpWlDhWQbjEzijNaHAkMQyJyqM2f3/view?usp=sharing
