### ISSUE TITLE
Hide Unavailable Books not working

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#36]
Hey Not that most people care (atleast I think they might not) but the Hide Unavailable Books Check box on the Feats Sheet doesn't work properly anymore. Not sure why but for 1 of my games I'm only allowed the Core books and Forgotten Realms books and when I check the Hide box and let it refresh I still get all the books showing for feats. Also Hide Epic Feats doesn't work either. I'm sure it could just be something with the VBA coding.

**Comment by AncestralD** [comment]
Well mine seems to work just fine.. did you hit the Button with "Calculate feat availability"?
![hide feats](https://cloud.githubusercontent.com/assets/10347610/9022725/b60f606c-3880-11e5-989b-3bc33aaa2dbb.PNG)

**Comment by TwistedFaith84** [comment]
Yea I hit the "Calculate Feat Availability" and it's not working on mine. Although I could be using v7.4.0.0 for the one it's not working on but other then that I made some small changes to my version (ie adding the check box for HP Max @ lvl 2-60 back in (info is already there just need to add the check box and have it link to "HPMax" (minus the Quotes)), Druid of Mielikki able to wear and use Metal armor and weapons/shields, Initiate Of Nature Druid and/or Cleric gaining the ability to rebuke/command plants creatures and animals, and a few other homerules specific for my games (but nothing major)) and it doesn't hide the books. it could just be maybe I just have to reinput all the info into v7.4.0.1

**Comment by TwistedFaith84** [comment]
Or it could also be the version of MS Excel Im using

**Comment by AncestralD** [comment]
Well i just tested the function on excel 2002 and 2013. and there were no problems with them there.
i am using v7.4.0.0
so what i can get from it. it might be something with the add-ons you made. 
in my tests i have marked alle three check boxes. maybe that will help?

**Comment by TwistedFaith84** [comment]
Possible but I dont need all 3 check boxes checked the feats from the DMG are ok. maybe you should try selection 1 check box at a time.

**Comment by AncestralD** [comment]
I have been testing the feat section for a time now, and  the checkbox with hide unavaible feat books works just fine. also does the checkbox with dmg feats. but i cannot get the epic feats to become hidden..

The feats books that become hidden are linked to the books you have marked in the options section.

**Comment by TwistedFaith84** [comment]
Ok it must have been something with my computer. The Hide Unavailable Feats works so does the Hide DMG Feats. The Hide Epic Feats All it Hides is ELH. So the VBA Coding for the Hide Epic Feats needs to be Fixed (more like update)

**Comment by Heliomance** [comment]
Can I close this as working properly?

**Comment by TwistedFaith84** [comment]
Yea you can close it but the Hide Epic Feats still isn't hiding all Epic Feats It's gotta be something in the VBA coding
