### ISSUE TITLE
Weird bug (reproducable) with Paladin class

### ISSUE THREAD

**Issue by Torvon** [Heliomance/HeroForge-Anew#37]
Hi. I get this bug both with old versions of Heroforge, and Heroforge anew. 
Open, make all nonsetting sources available, open flaws tab, select stats 16 10 12 12 10 16, Magical gain +2dex +2con -2wis +2cha, select Rock Gnome, Select Paladin level 1 and 2, enter 10 for lvl 2 hitpoints.

At this point already, in Character Sheet II the Divine Grace Paladin bonus is not shown anymore in the Special Abilities, neither does it show in the Character Sheet I misc bonus to saves. 

I had this 3 times now, using different versions of excel on 2 different computers. Sometimes it takes a bit longer (e.g. I add weapons and armor). But it always comes up within 10-15 minutes.

**Comment by Heliomance** [comment]
Could not reproduce. The only things I can think of is that Divine Grace will not apply if you don't have a Cha bonus, or if you're not Lawful Good.
