### ISSUE TITLE
Warshaper natural attacks

### ISSUE THREAD

**Issue by AncestralD** [Heliomance/HeroForge-Anew#39]
i am trying to create a shifter barbarian/warshaper.
but i have encountered a couple of things i hope one you can help me with.

do you know how i can make natural attacks a permanent asset in the attack window?

Can you tell me where i can edit feats? the feat shifter savagery activates upon shifting instead of shifting and rageing.

is it possible to create your own class variant? i would like to have a totem variant from unearthed arcana.
if that is not possible, do you know where i can change the class abilities of the barbarian?

i think that was it for now.
i hope you can help me.

**Comment by Heliomance** [comment]
As it's currently coded, it's not possible for it to display natural attacks when you're not in a form that has them. Making it do so would be a major overhaul, and I'm really not sure how it could work.

Feat descriptions and such are on the feats page in hidden columns. If they have numerical effects that affect other things, the  calculations for that are wherever the thing they affect gets calculated.

There is a Custom Class sheet, accessible using a button on the Options tab, and the Barbarian's abilities are on the hidden Class Abilities tab. Totem variants are on the list to go in at some point, but development's currently on hiatus due to real life and other projects, so they won't be turning up for a while.

**Comment by AncestralD** [comment]
Would it be possible to get the natural attacks if the warshaper got the natural attacks in a way like the longtooth shifter gets access to them?

Unfortunatelly i can't make heads or tails with the way most of the windows are built. i'm not enough of af wiz to do that.. 

How would the custom class work with the rage? and such? would i be able to make it do calculations?

Thanks for the help. I will try to figure out something..

**Comment by torrasque666** [comment]
I know how to code it so that they appear in the Class Weapons and Armor page, but I'd need to know if you want me to code /every/ natural attack possible, or just the ones in MM1 (which is where it directs for dice size)

**Comment by AncestralD** [comment]
Well, actually i think i got everything sorted out. i went into race abilities and located the cell that activates the natural attack form the longtooth and claw shifter trait, and just hotwired the cell to stay active.  
Then i went to the class weapon & armor sheet and and fixed the shifting savagery from there.

and for the alternative class features i went to the class abilities sheet. removed those which had no mecanical effects and added the new features in the writing.  i had some trouble removing fast movement but i located a cell named speedwithrun hidden in the armor sheet. went into a table with enhancements to speed and removed them.

So.. i got the stuff done and everything seems to work as it should, the natural attacks change when i activate savagery by rageing and shifting. 
           But i feel kinda dirty, tampering with the sheet like that

Do you have another method? I would love to know how you would do those things! 

 Here is a link to the character
https://drive.google.com/uc?export=download&id=0B-20RsivPL3WY1VDdS0xeFJwMGM

**Comment by AncestralD** [comment]
@torrasque666 How would make all the natural attacks available?

**Comment by torrasque666** [comment]
@AncestralD Basically, you just have to add lines in the "ClassAttacks" section of the Tables page, where things like Slimelord or the various Animal Lords give natural attacks that say something along the lines of "X+4+0+1" (adjusting for how a natural attack uses strength and the size of its damage dice at Medium. Then, just extend all of the lines under ClassAttacks [U20] to include them.

**Comment by AncestralD** [comment]
@torrasque666 Sorry im having a bit of trouble understanding what to do. i can find the cells you are refering to, but i dont see what to do with them.

**Comment by ThAlEdison** [comment]
As warshaper is written, you could add
this: =IF(WrpLvl>=1,"Bite+5+0+1,Claws+4+0+1,Foreclaws+4+0+1,Gore+5+0+1,Head
Butt+5+0+1,Hooves+4+0+1,Horns+5+0+1,Pseudopods+4+0+1,Slams+4+0+1,Stamps+4+0+1,Sting+4+0+1,Tail
Slap+5+0+1,Talons+4+0+1,Tentacles+4+0+1,Wings+4+0+1","") for the morphic
weapons.
Technically it takes a move action per morphic weapon to create them.  The
text says appropriate damage according to size.  The damage values are
taken from table 5-1 in the MM.
The structure is <Name of Attack>+<number indicating damage
code>+<increase/decrease in size>+<-1=no strength, 0=1/2 strength, 1=full
strength, 2=1 1/2 strength>
It's unlikely any of these will be your sole natural weapon, so none of
them have 1 1/2 strength.

~Erick A. Cobb

**Comment by AncestralD** [comment]
Thank you all, for the help!! i finally made it work.. You are all wonderful Excel Wizards!
