### ISSUE TITLE
OpenOffice.org 4.1.1 BASIC runtime errors

### ISSUE THREAD

**Issue by GamerGoddessDin** [Heliomance/HeroForge-Anew#4]
I receive the error messages listed below upon loading the document with macros enabled in OpenOffice.org Calc 4.1.1:

'91' object variable not set.
'35' InStrB (3 times)
'91' object variable not set (2 times)
'35' InStrB

Messages are listed in order of when I received them during loading. I'm going to see if it will still function with those errors but I'm not holding out too much hope...

**Comment by GamerGoddessDin** [comment]
Yeah, this ain't working. Which version of Excel does this document require? I'll have to acquire a copy to use this with since macros probably aren't easy to make work between OO.o and MS Office.

**Comment by ThAlEdison** [comment]
I've run hero forge on 2003, 2007, 2010, and 2013.

I've run anew on 2010 and 2013.  A friend has run it on 2003 (I think).

**Comment by GamerGoddessDin** [comment]
```
Works on 03? That's good. I know how to use that GUI and had decided
to download it before I got an answer.

On 02/09/2015 18:55, ThAlEdison wrote:

I've run hero forge on 2003, 2007, 2010, and 2013.

  I've run anew on 2010 and 2013. A friend has run it on 2003 (I
  think).
  On Feb 9, 2015 6:10 PM, "GamerGoddessDin"
  <notifications@github.com> wrote:

  > Yeah, this ain't working. Which version of Excel does this
  document
  > require? I'll have to acquire a copy to use this with since
  macros probably
  > aren't easy to make work between OO.o and MS Office.
  >
  > --
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/Heliomance/HeroForge-Anew/issues/4#issuecomment-73618970
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Heliomance** [comment]
As far as I know, it works on all versions of Excel. Unfortunately, due to the incredibly heavy VBscripting, it doesn't work on anything except Excel. Adapting it to work with other spreadsheet programs would be a mammoth undertaking, and I'm afraid I wouldn't know where to start, or even if it's possible to write a cross-platform version. If anyone knows more than me, I'd be happy to collaborate on adapting it, though.
