### ISSUE TITLE
Open Office Compatibility?

### ISSUE THREAD

**Issue by Felismagus** [Heliomance/HeroForge-Anew#40]
Is the setup incompatible with Apache Open Office?
Downloaded ZIP and extracted to desktop. Verified all files in folder and match load dates.
On load, the .XLS file prompts contains links to other files, should they be updated, selected yes.
Have opened security settings to allow Macros to operate.
Opened file properties for .XLS and unblocked

On selecting a number of fields/buttons getting error
![scripterror](https://cloud.githubusercontent.com/assets/13729742/9170442/df518548-3f30-11e5-8344-a57f2fa66758.png)

No error on Deities list, 
Unearthed Arcana: no error on the Fraction BAB or Save -  errors on Gestalt/Traits/Flaws
No errors selecting any items under Non-Setting Sources, (incld Monstrous)
Under "Settings" all selections return errors (except: Underdark & remaining list from Age of Mortals down)
Everything below "Optional Tabs". (section3) 

If I am missing a step, any assistance would be appreciated.

**Comment by TwistedFaith84** [comment]
## Yes HeroForge is not compatible with Open Office.

Sent from myMail app for Android Monday, 10 August 2015, 06:25AM -05:00 from Felismagus < notifications@github.com> :

**Comment by TwistedFaith84** [comment]
## You have to use EXCEL only cause of the Macros and VBA.

Sent from myMail app for Android Monday, 10 August 2015, 06:25AM -05:00 from Felismagus < notifications@github.com> :

**Comment by Felismagus** [comment]
Thanks for the confirmation. Have to see if I can scrounge up a copy of MSOffice. was looking forward to using this app.
