### ISSUE TITLE
Kobold Tricks

### ISSUE THREAD

**Issue by Erthafein** [Heliomance/HeroForge-Anew#41]
are the kobold "rite of Passage" and "greater rite of passage" able to be tracked on the spreadsheet somewhere?

Sorry If I am just plane missing it.

**Comment by Heliomance** [comment]
Not currently, no. I think one of them is a feat isn't it? That'll be easy enough to add. Not sureabout how to bestdo the other.

**Comment by Erthafein** [comment]
The whole process does require a feat (Draconic Reservoir) to complete.
Mainly, it would require a way to track a bonus level of Sorcerer and the
allotment of spells per day for such.

While I have you, Is there an easy way to add the variant races from
Unearthed Arcana?  I'm still kinda picking my way through learning the
spreadsheet, and I know jack & squat about excel, so I can't seem to find
it.

Thanks

On Fri, Aug 14, 2015 at 3:25 PM, Heliomance notifications@github.com
wrote:

> Not currently, no. I think one of them is a feat isn't it? That'll be easy
> enough to add. Not sureabout how to bestdo the other.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Heliomance/HeroForge-Anew/issues/41#issuecomment-131214454
> .

## 

Roger L. McEldowney

2437 Lakebridge Ln.
Hilliard, OH  43026

(614) 565-9567

**Comment by torrasque666** [comment]
Greater Draconic Rite of Passage would be better used in Spellforge, until its functionality is added back in.

**Comment by Heliomance** [comment]
For races, you want the Race Info tab, and potentially the Race Abilities tab. Add them as entirely separate races.
