### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Erthafein** [Heliomance/HeroForge-Anew#42]
Is there a way to open a character from an older version of HeroForge in a newer version?  I was hoping not to have to remake a character from scratch....

**Comment by torrasque666** [comment]
Depends. How old is it? Because if its before when Heliomance added in the version check area on the Export Page, then you're kinda out of luck. But if its one of the newer versions, you can just change the version it lists on the Export Page, save the character, and reload in the new version.

**Comment by Erthafein** [comment]
Thanks for the quick answer.  I wasn't able to get it to work, but I appreciate the answer none-the-less.

**Comment by Heliomance** [comment]
That version check thing has always been there. I changed the logic slightly a while back, but editing the version number ought to work anyway. That said, I really don't recommend it - it will likely produce some really funky effects.

I plan on changing to XML-based save files at some point, which should hopefully stop it breaking on subsequent updates.
