### ISSUE TITLE
Request:Convert to XLSM format

### ISSUE THREAD

**Issue by timoc** [Heliomance/HeroForge-Anew#43]
Hi,

I would like to request porting to an open XML (XLSM/ODT) format. The XLSM or ODT format is actually a zip file created from a source XML files, you can use github more effectively to patch and merge changes in the source XML, rather than by hand.

For those using earlier versions  is trouble opening xls files in later versions of office, and earlier versions of office can be made compatible: https://support.microsoft.com/en-us/kb/924074

My initial investigations seem to imply that practically ODT is the better XML format. When i save as XLSM and ODT from Excel 2013 i find that the XLSM file contains 9016 XML files, and the ODT version contains 14 files.

```
~/HeroForge-Anew $ unzip -t HeroForge\ Anew\ 3.5\ v7.4.0.0.xlsm | grep -c testing
9061
~/HeroForge-Anew $ unzip -t HeroForge\ Anew\ 3.5\ v7.4.0.0.ods | grep -c testing
14
```

update:
XSLM is supported by something called vbagit, which is also interesting.  http://ramblings.mcpher.com/Home/excelquirks/vbagit/gettingstarted

**Comment by Heliomance** [comment]
I vaguely remember trying to save as XLSM before and it not working terribly well. Don't remember why offhand, but I'm going to have another go at some point.

**Comment by timoc** [comment]
I for one have noticed that working with xlsm files is faster, because it saves faster. Do not ask me why. 

My experience with the xlsm version has been good - i have been using an xslm version of 6.4 for some time. it boils down to complaining about three things.

The Office 2013 ods (and xlsm) exporter complains about some definitions, that it changes on save. they seem to be related to compound commands on the buttons.

```
dnn73 to  _dnn73
HF_Resetclearoptions:=False;askConfirm:=True to _HF_Reset_clearoptions__False_askConfirm__True
HF_Reset_clearoptions:=False;askConfirm:=True to _HF_Reset_clearoptions__False_askConfirm__True
```

**Comment by timoc** [comment]
Have done most of the work for this in my fork so can close this for the moment. 
My thoughts so far are to make a development branch with the source XML files (from an XSLM or ODT file) in it, so that developers can diff and merge those easier, then the maintainer can merge and 'compile' the release from it.

**Comment by Heliomance** [comment]
How would I go about doing that? I'm purely hobbyist, I don't have a clue about proper software development practises and the like, and I'm not terribly confident with XML either. I want to learn though - one of the next things I want to do with this is change the save file format to XML, to hopefully futureproof it a bit and improve save file forwards compatibility.

**Comment by timoc** [comment]
Ok. I'm a professional, so maybe have a different perspective. I've an idea, and will put it all into a separate branch first. It breaks down to:
- DRY (Do not repeat yourself) practices:
  - Do not use IF constructs () or similar in cell formula, use a macro. Its easier to maintain. 
    That is, if the logic is in a macro, the fix only has to be in the macro. 
    Its also easier to use version control on macros.
  - Make all Ranges separate sheets or have unique column and row
  - All ranges with startRangeName and endRangeName, to make validating range definitions easier.

There is probably more, I'm re-teaching myself MSBasic after 30 odd years, so best captured in a README or something.

My biggest fear is that changes will not port to the XMLS version.

**Comment by TwistedFaith84** [comment]
Ok i dont understand but why port HeroForge over to XML? Isn't XML mostly used for the Web?

**Comment by chaoscommencer** [comment]
XML is basically a convenient tag-based storage mechanism. It makes adding new properties, say for future features, pretty much as simple as adding a new tag. Not only is it easy to expand the data files for future versions, but XML is also human-readable. It is used extensively outside of web-based applications as well.

**Comment by timoc** [comment]
What he said, plus, 'version control' 
This means others can work on the same version of the spreadsheet, making different features, and merging into one new one.

**Comment by Heliomance** [comment]
Pretty sure GitHub still counts .XLSM files as binaries, doesn't it? That means merging different branches is still not easy.

**Comment by timoc** [comment]
An XSLM file is a straight zip file. The idea i have is to keep the 'source' XML under git for development, and compile zips for distribution.

**Comment by Heliomance** [comment]
How would I go about doing that? I've turned my local copy into an XLSM, thanks to your work (interesting side effect, it's got rid of the ugly black border on the checkboxes). How would I go about letting Git see it as XML?

**Comment by ThAlEdison** [comment]
Rename as .zip, and unzip.  Or open using something like 7-zip.

~Erick A. Cobb

**Comment by Heliomance** [comment]
...but presumably you can't edit the workbook effectively in that format. So while it might be better for the purpose of diffs, it's not actually useful for develpment.
