### ISSUE TITLE
Adding New Buffs.

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#44]
How exactly do I add new Buffs. I'm trying to add primal hunter, primal instinct, primal senses, & primal speed. among others and I'm lost.

**Comment by Heliomance** [comment]
Just add a checkbox on the Buffs page, link it to a cell on ExportSheet near the other buffs, name the cell it's linked to, then go and add in the adjustments it makes in the appropriate places. For example, if one of them gives +4 spot, you'd go to the Skills tab, unhide the calculation columns, and add `+IF(BuffName,4,0)` to the appropriate column of the Spot row.

Making it clear when you reset the sheet involves messing with the VBScript.

**Comment by TwistedFaith84** [comment]
ahh ok well the VBAscript I'd be completely lost but the other stuff I can do
