### ISSUE TITLE
Familiar Skill Calculation

### ISSUE THREAD

**Issue by chaoscommencer** [Heliomance/HeroForge-Anew#47]
Reproduction steps:
Wizard, lv 1, add familiar (any).

Final skill values (for the familiar) result in ####, due to type errors in the calculations for those skills in the DA and DB columns.  This may happen for other skills (I have the default hide untrained skills checked), but I am at least seeing this error for Intimidate.

**Comment by chaoscommencer** [comment]
I noticed in your recent patch there was a reference to fixes for animal companion and familiar sheets. Did that address this bug?

**Comment by Heliomance** [comment]
Fixed for v8.0
