### ISSUE TITLE
Spellforge etc?

### ISSUE THREAD

**Issue by timoc** [Heliomance/HeroForge-Anew#51]
Hi,

The original Heroforge site contained more than the character sheet. Are the other sheets available? like the spell forge etc?

**Comment by torrasque666** [comment]
https://github.com/TwistedFaith84/DND_Gaming_Tools

Twisted Faith has most of them.

**Comment by timoc** [comment]
I discovered the original sources are still kind of available.
http://nzcomputers.net/heroforge/downloads/

**Comment by TwistedFaith84** [comment]
Well thanks to that link and IDM (Internet Download Manager) I now have everything that was on that link. I've been thinking about putting everything on Dropbox or something similar to make it easier to download.

**Comment by timoc** [comment]
How re-usable are those sheets? Some of them, like spellforge compliment Heroforge, and are usually used side by side.

**Comment by TwistedFaith84** [comment]
Well the 3.5 Animal Companion is by far better then the one currently in HeroForge it just needs more companions added (no offense Heliomance) there are a few other minor addition/changes that it could use also. MountForge I haven't really looked at it. As for most of the others they are mostly for the DM/GM (some of them could use some work to make them better but they are good for what they are at this point). The Magic Item Creator is pretty good but needs to be updated, add more slots for selection, and add more spells/abilities. The rest of the stuff Just ask me and I'll let you know if I know.

**Comment by torrasque666** [comment]
I'm dabbling with the Magic Item Creator. I have Melee Weapons with 9 +X enhancement slots plus the base enhancement slot, and and working to update the "non enhancement bonus" section. Currently, I have all the Melee Weapon enhancements from the MIC added.

**Comment by timoc** [comment]
FWIW, i think the magic item creator would be much better in HF. there needs to be something to add custom items.

I'm not bothered with features so much at the moment, as on trying to get these into XSLM or similar so i can share changes with others easily.

**Comment by torrasque666** [comment]
True. Using XSLM would make my feat update so much better (Currently using a shitton of array formulas, which in turns in a massive drain on processing power.)
