### ISSUE TITLE
HeroForge Database

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#52]
You know I just thought of it. I know there are sites that contain database files (http://www.andargor.com/) for D&D 3.0/3.5 stuff and I know at some point you want to split HeroForge up into smaller chunks and have the info be pulled from the others so I guess the question is if you had the some info being pulled from the Large Database files that you can get from various sites like (http://www.andargor.com/) would it help speed up the process.

**Comment by Heliomance** [comment]
Available databases are:
- Usually SRD only
- Not in a format I control
- Not under my control at all

I can't imagine that using such a thing would save any time at all.

**Comment by TwistedFaith84** [comment]
I'm pretty sure that the one at the site I mentioned isn't SRD only though I know it's not complete. As far as format and control goes well format you can always change to suit you needs and control can be taken take of by finding a site to host your own version (mods) of the database and having HeroForge pull from that database. I'm not trying to convince you or anything just saying that those are a few workarounds I thought of in a matter of mins. I sure you could have thought of them also (if you all ready haven't) had you probably not had other stuff on your mind.

**Comment by chaoscommencer** [comment]
Interesting, so is a copy of the database somehow embedded into the Excel spreadsheet?  Or have you manually entered those values into the spreadsheet (or does it perform online lookups at run-time for the required data)?

**Comment by Keldin** [comment]
In a very real way, all spreadsheets are databases.  The only real difference in a spreadsheet is there is less control of the data type and you can include formulas.  Pull up any of the info tabs (I'm looking at Class Info right now) and scroll across, line by line filled with data specifically relevant only to line.  That's a database - the rows are individual records, and the columns are fields in the database.  The real advantage to using a database over a spreadsheet is that databases are made to work with larger amounts of data -- the more data in a spreadsheet, the slower it's going to be.  That's not necessarily the case in a database.  It's sometimes the opposite.

**Comment by chaoscommencer** [comment]
... :|. Ok, so the data was manually entered, thanks. (I am aware of the differences between spreadsheets and databases)

**Comment by Heliomance** [comment]
Also databases are set up to make linking various bits of it together easier, in most cases. And I'm pretty sure it makes it easier to do things like make tables, each record of which is also a table in its own right.
