### ISSUE TITLE
Creature Info Data

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#55]
Hey I just took a look at the Creature Info Data you uploaded and wanted to let you know that Custom Familiar has a few spots that are giving of #Ref errors. Just thought you should know that.

**Comment by Heliomance** [comment]
I'm entirely unsurprised. I never got Custom Familiars working properly, and now I'm making massive changes to the structure of the sheet, I'd be very surprised if I hadn't broken everything. I'll make everything as stable as possible before I update the Main branch, but Custom _anything_ functionality may be missing for a few releases.

**Comment by TwistedFaith84** [comment]
Well I noticed that for the Custom Familiar the data that is reading is pointing to your dropbox link for HeroForge-Anew. It might work better if you just had the data being pulled from the Custom Familiar Sheet of HeroForge-Anew. That way when someone actually fills out the Custom Familiar it will get the data it needs as its custom and not everyone else is going to be using it. Thats the way it should be for Custom anything. It could also be why your not getting Custom Familiar to work properly.

**Comment by Heliomance** [comment]
...it's a WIP. I'm not expecting it to work at the moment.

**Comment by TwistedFaith84** [comment]
I understand that it's a WIP. I just figured that you what I suggested is the fix you could take care of it when you get a chance and be done with it. And as I say that I just realized that with you splitting the sheets you would have to change it with each new version thats released (I think).
