### ISSUE TITLE
How are we to go about updating the Data Sheets your uploading?

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#56]
Hey I like the idea of splitting up the data sheets from HeroForge but was curious on how would we go about updating and uploading the data so that new additions/corrections get saved to a master data file for everyone you to use???

**Comment by Heliomance** [comment]
Currently it's a WIP and subject to change at any time, so you wouldn't. Once it's finished and stable though (once version 8.0 is released and I update the Main branch), you could modify your copy of the data sheet, then submit a pull request to merge it into the project. Separate files mean that it won't have incompatibilities if I've modified a different part of HeroForge, so assuming I haven't coincidentally also made changes to the same sheet, it will be very easy to just pull the updated version into the project.
