### ISSUE TITLE
Split static data tables into separate sheets for modularity and version control purposes

### ISSUE THREAD

**Issue by Heliomance** [Heliomance/HeroForge-Anew#57]

**Comment by Heliomance** [comment]
Weapon tables extracted, need to move unarmed strike and natural attack damage calculations back to the main workbook.
Creature Info and Race Info tables extracted and combined, working on overhauling racial skill storage

**Comment by TwistedFaith84** [comment]
to bad they dont have a Thumbs up or something like that on GitHub

**Comment by Heliomance** [comment]
WeaponInfo sheet fully extracted and converted to csv.
Working on pulling all remaining formulae out of CreatureInfo sheet prior to conversion to csv.

**Comment by Heliomance** [comment]
CreatureInfo sheet fully extracted and converted to csv (back in September, forgot to update this ticket)

**Comment by Heliomance** [comment]
Primary data tables have been extracted and converted to csv. More may follow in the future, but for now I'm closing this ticket.
