### ISSUE TITLE
Ranger (Elf Substitution Levels) 4th Level Animal Companion (Elven Dog)

### ISSUE THREAD

**Issue by rgordey** [Heliomance/HeroForge-Anew#59]
Companion Sheet Has error on Bite Attack Calculations. Shows NULL.

**Comment by torrasque666** [comment]
aye. that's because apparently, it lacks the necessary call info. This can be fixed by adding "+6+0+2" after the bite in the attacks column

**Comment by rgordey** [comment]
That fixed it. Thanks.

**Comment by Zukibird** [comment]
Trying to fix heavy horse and having problems in "weapon/total attack bonus/damage/critical/size" fields and looking for help. If I can get the formula for the damages I would be willing to go in and fix some of the other normal animals as well.

**Comment by Heliomance** [comment]
Elven Hound attack stats added in 8.0. Volunteers to do more creature data entry would be welcome, now that the CreatureInfo table is properly mergable.
