### ISSUE TITLE
Ranger (Elf Substitution Levels) 1th Level Favored Enemy (Servants of Lolth)

### ISSUE THREAD

**Issue by rgordey** [Heliomance/HeroForge-Anew#60]
On Charter Sheet II Favored Enemy shows as Vermin and Not Servants of Lloth.

**Comment by torrasque666** [comment]
Its actually a problem for normal rangers too. For some reason the Favored Enemies table the Tables sheet doesn't have a slot for Outsiders (Fire) and thus screws up everything after its place.

**Comment by Heliomance** [comment]
I was thinking I might restructure how Favoured Enemies work a bit anyway. I'll sort this at the same time.

**Comment by Heliomance** [comment]
Okay, Favoured Enemy calculation is a mess, but I think I've fixed this issue now. I do need to look into overhauling it properly, but that's a big enough job that I won't do it for 8.0.
