### ISSUE TITLE
How would I find the full data for weapons in the excel sheet?

### ISSUE THREAD

**Issue by Austin601** [Heliomance/HeroForge-Anew#62]
Hi, I was wondering if there was a location for all the weapon data in the excel sheet so I could copy it down for use in game, without having to go through each drop-down option. Thanks.

**Comment by torrasque666** [comment]
Do you mean like damage dice and all that? Because you're looking for the sheet "Class Weapons and Armor". You'll need to do some cross-referencing though. Its easier to just copy down the values from the Attacks sheet.

**Comment by Heliomance** [comment]
Yes, extracting that info from the data table is a pain, because of the way it's stored in order to properly calculate size changes. It really is easier to go through each drop-down option.
