### ISSUE TITLE
Minor Fixes

### ISSUE THREAD

**Issue by ThAlEdison** [Heliomance/HeroForge-Anew#63]
Note attachment has incorrect extension to trick github
1. Slightly wrong name references
1a. TemplateAcquiredInt: currently ='Template Info'!$AF$3:$AF$8; should be ='Template Info'!$AF$4:$AF$12
1b. TemplateSelected: currently ='Template Info'!$A$3:$A$8; should be ='Template Info'!$BC$4:$BC$12 (? not sure about this one, ='Template Info'!$A$4:$A$12 may also work)
1c. TemplateSelectedLvl: currently ='Template Info'!$AU$5:$AU$12; should be ='Template Info'!$AU$4:$AU$12
1d. TemplateSelectedName: currently ='Template Info'!$A$5:$A$12; should be ='Template Info'!$A$4:$A$12
2. In Cell TemplateRacialSkillMod ='Template Info'!$AI$1, the formula is currently =IF(HasTemplate,RANGECONCAT(", ",TRUE,AI$4:AI$12),""); should be =IF(HasTemplate,RANGECONCAT(",",TRUE,AI$4:AI$12),"") with one less space
3. The list of Skills for Ogre Titan ='Template Info'!$AI$52 is currently "Concentration+8,Intimidate+8,Knowledge (arcana)+8,Knowledge (history)+8,Listen+10,Search+10;Sense Motive+8,Spot+10"; it should be "Concentration+8,Intimidate+8,Knowledge (arcana)+8,Knowledge (history)+8,Listen+10,Search+10,Sense Motive+8,Spot+10" changing the semi-colon between Search and Sense Motive to a comma
4. The cell range ='Class Weapons & Armor'!$AW$289:$AW$311 should be shifted one column to the left via copy & paste (as opposed to cut&paste or deleting cells) so that the Name TblNaturalAttacksCon matches where the table data is.  Alternately, you could change the Name to refer to column AW instead of column AV, in that case ='Class Weapons & Armor'!$AV$312 should be moved one column to the right

![heroforge anew 3 5 v7 4 0 1 zip](https://cloud.githubusercontent.com/assets/10685976/10973504/5a34a22a-83a3-11e5-931c-96dce021c40c.jpg)

**Comment by ThAlEdison** [comment]
Original extension is .zip

**Comment by Heliomance** [comment]
Those all look to be in parts of the sheet that are getting restructured for v8.0. I'll leave the ticket open for now, but it's likely it'll solve itself as part of the restructure.

So I know what to look for, what are the symptoms of these mistakes?

**Comment by ThAlEdison** [comment]
1. When using templates (especially acquired templates) skill points are
   wrong
2. When using more than one template,  some skill modifiers given by the
   template will be missing
3. It causes a #VALUE error in the skills sheet that spreads all the way to
   the monsters Tyler stat block on the stats sheet. But only when the
   template with the incorrect skill formatting is selected.
4. The dropdowns for improved natural attack don't work

**Comment by Heliomance** [comment]
First three issues fixed in 8.0. Fourth issue is irrelevant due to creature data restructure.
