### ISSUE TITLE
Two Weapon Fighting not calculating correctly??? Probably??

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#67]
This issue coincides with https://github.com/Heliomance/HeroForge-Anew/issues/66
Again while trying to make a 10th lvl thrown weapon character using Adamantine Shurikens (Ninja 6/Master Thrower 4) would put my attacks at +14/+9 when TWF it's +12/+7 which is fine but when trying to add a +1 bonus or higher the calculation is off by +1. I know that being an Adamantine weapon automatically make the weapon Masterworked but doesn't it still add the +1 and higher bonus?

**Comment by Silinde** [comment]
It sounds to me like it is calculating correctly,  Keep in Mind that Masterwork adds +1 to hit (not damage), Making it Magically +1 gives it an additional +1 to Damage, If it is made out of Adamantine then it would already have the +1 from Masterwork calculated.  Try puting it in as a normal check the stats and then switching it to Adamanitine, it should not change at all.

**Comment by TwistedFaith84** [comment]
@Silinde yea it's calculating correctly for the hit and damage but still having the other issue from https://github.com/Heliomance/HeroForge-Anew/issues/66
