### ISSUE TITLE
Spell Points

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#69]
Is there a way to have Spell Points Be calculated for those that want to use Spell Points?

**Comment by Heliomance** [comment]
No, by design. That functionality was migrated to SpellForge years ago, because HeroForge was getting too big. I do plan on resurrecting SpellForge at some point, though, so that'll happen eventually.

**Comment by TwistedFaith84** [comment]
While I knew you planned on resurrecting SpellForge at some point that's one reason I asked.
