### ISSUE TITLE
Tashalatora and monk bugs

### ISSUE THREAD

**Issue by MonkeyBotSA** [Heliomance/HeroForge-Anew#7]
Couple bugs here. First is related to that HRES/HRECS bug that was messing up class selection and stuff. The bonus monk feat tables still reference HRES insted of HRECS so instead of Monastic training as a potential monk bonus feat you get a NAME error.

Second is a bit missed from Tashalatora implementation: Flurry of Blows on the attacks page. You need to account for the manifesting class level to get full bonuses and attacks. On attack 1 you need to add "+IF(FtTashalatora,VLOOKUP(TashalatoraClass,TblManifesterRef,3))" to the monk level calculation in cells D3 and D4 then do the equivalent for the other attacks.

I'm only so-so on the Excel stuff (it takes me a while to find the fixes sometimes) but if you'd like me to fix bugs when I find them and upload new versions I can. Just let me know, otherwise I'll just submit issues.

**Comment by Heliomance** [comment]
OH DAMMIT. I've lost count of the number of times I've run a Replace All on HRES. It keeps telling me it's found everything. That's really driving me nuts. I really hope I've got them all now.

I'll look into that, thanks for the heads-up. Just submitting issues is easiest, though providing solutions along with them is appreciated. The problem with fixing and uploading new versions is that there's no easy way to merge the changes with my copy, which may very well not be the same as the latest release.

**Comment by Heliomance** [comment]
Okay, fixed both those issues. They'll be out in v7.4.
