### ISSUE TITLE
Older versions of hfg

### ISSUE THREAD

**Issue by johannes-z** [Heliomance/HeroForge-Anew#77]
I have some older characters created with heroforge 6+ created and obviously can't open them with Heroforge 7+.
Is there anyway I can extract the data to recreate the character? Or does anyone have a copy of heroforge 6.2.0.3? The old heroforge mirror is down.

**Comment by TwistedFaith84** [comment]
I have a copy that I can put the link up for you. BTW is it 6.2.0.3? or 6.2.0.3a?

**Comment by TwistedFaith84** [comment]
here is the link for 6.2.0.3a
https://www.dropbox.com/sh/g336g1fe7jwwzdp/AACrtnPsAaMjhIpUBOCHaQS9a?dl=0
and 6.2.0.3
https://www.dropbox.com/sh/hmyzk0eu5vsakpb/AAAL9-5t723YY8D-IIk2plJda?dl=0

**Comment by johannes-z** [comment]
Much appreciated, thanks!

**Comment by TwistedFaith84** [comment]
NP Welcome
