### ISSUE TITLE
Available Feats Count does not offset count for bonus feats

### ISSUE THREAD

**Issue by unRealElite** [Heliomance/HeroForge-Anew#88]
While attempting to fill out the feats tab for my character, I saw the Available Feats count dip below 0 after picking my bonus feat last. 

![before](https://cloud.githubusercontent.com/assets/2671750/15660562/0b0ef28e-2693-11e6-855f-15c724da6900.png)
![after](https://cloud.githubusercontent.com/assets/2671750/15660561/0b0a4a22-2693-11e6-964d-588728946db8.png)

**Comment by Zukibird** [comment]
Is it because you do not have a class selected for bonus feats in the drop down menu above?

**Comment by TwistedFaith84** [comment]
Actually its because the number listed in the available feats is for total number of feats available (including bonus feats) so if you used up all available feats and still have 1 bonus feat and you select a bonus feat you have 1 to many feats selected.
