### ISSUE TITLE
Dweomerkeeper conversion is no quite finished

### ISSUE THREAD

**Issue by MonkeyBotSA** [Heliomance/HeroForge-Anew#9]
One of the changes you converted the Dweomerkeeper PrC from F&P to the Complete Divine Web Enhancement version. It's mostly correct except that it it giving bonus feats at levels 1, 5 and 9 of the PrC which it should not. I'm assuming that is a leftover from the previous version. Also in the Bonus Feats dropdown on the Feats tab there is still a listing for Dweomerkeeper which should probably be removed since the PrC no longer provides bonus feats.

Oh and there only seems to be locations for 3 Mantle of Spells entries on the Prestige Class III page, should be 5,  and the "x"es never become check marks.

**Comment by Heliomance** [comment]
Fixed in 7.4
