### ISSUE TITLE
Yuan Ti, Anathema Alter Form is wrong

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#92]
Just thought I'd let you know that for some reason the Yuan Ti, Anathema Alter Form is wrong it is reading the one for the regular Yuan Ti. The only fix that I found for this to change Cell F1 in the Racial Abilities sheet from "=Race" to "=FullRace" but I'm not sure what if any problems that might cause for other races or if it will make it not show all the abilities for the selected race.

**Comment by TwistedFaith84** [comment]
Ok through trial and error I figured out that making the change I listed above does cause it to not list all the Abilities for some of the races. I only thing I can think of to fix it is to go through race by race and see what comes up and what doesn't and try and figure out a fix for the ones that need to be fixed.
As of now I have the first Yuan Ti racial ability for Alter Form  listed as
="× Alternate Form(Sp): You can assume the form of a Tiny to "&IF(FullRace=A821,"Huge","Large")&" viper." 
that way when it comes up (which is the first one to come up) it should list the right size for the right subrace regardless.

**Comment by Heliomance** [comment]
On testing, Yuan-Ti Anathema results in both Alternate Form abilities being listed on the character sheet. Given that any workaround I put in for this would be unavoidably inelegant, and that I'm trying to move in the direction of less calculations being done on the Racial Abilities sheet (I'd like to move that to an external datasheet as well at some point), I'm not going to fix this.
