### ISSUE TITLE
Natural Bond from Complete Adventurer 

### ISSUE THREAD

**Issue by ChopperDan** [Heliomance/HeroForge-Anew#98]
I noticed that there was no Fleshraker from MM3 as a Druid companion. So I was trying to add it. (I've almost figured it all out)
In the process I added Natural Bond to my character and noticed that it doesn't add the 3 levels for the animal companion. So, naturally, I"m trying to modify it so it does.  
I'm kind of stuck. I'm not that good in excel and am googling around looking for the proper formula, syntax etc... 
I'll gladly share the Fleshraker entry and Natural Bond modifications to the project once I complete them.
Thanks!
-Dan

**Comment by ChopperDan** [comment]
So, I fixed it... Maybe.
Under the "Creature Info" Tab I modified "CompanionLevel" formula from INDEX(BG$7:BG$226,CompanionIDx)
to
=IF(Feats!O679,IF((INDEX(BG$7:BG$226,CompanionIDx)-3)<=1,1,INDEX(BG$7:BG$226,CompanionIDx)),INDEX(BG$7:BG$226,CompanionIDx))

I'm sure it could be neater, but it appears to work. for now...

**Comment by Heliomance** [comment]
CreatureInfo tab is deprecated, I'm in the process of splitting it out into a separate sheet. When that's done, adding more critters should be a lot easier. I'll make a note that I need to double-check the Natural Bond calculations though.

**Comment by Heliomance** [comment]
**Fixed in 8.0.**
